"""Add work_type to Job model

Revision ID: 641d427712f2
Revises: 815a159831de
Create Date: 2025-05-27 09:11:38.356661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '641d427712f2'
down_revision = '815a159831de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment_likes')
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('work_type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_column('work_type')

    op.create_table('comment_likes',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('comment_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'comment_id')
    )
    # ### end Alembic commands ###
